name: Deploy Flask App

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up SSH
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

    - name: Copy files via scp
      run: |
        scp -r ./* root@4.227.163.242:/var/www/html/flask-hello-world

    - name: Restart Flask service
      run: |
        ssh root@4.227.163.242 'sudo systemctl restart flask-app'

